# Generated by Django 5.2.11 on 2026-04-14 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anuncios/')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DefinicaoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_suspensa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TOTAL', 'Todos os Utilizadores'), ('FILTRADO', 'Por Curso/Ano'), ('PARTICULAR', 'Utilizador Específico')], default='TOTAL', max_length=20)),
                ('curso_alvo', models.CharField(choices=[('GPSI', 'Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Todos')], default='nenhum', max_length=10)),
                ('ano_alvo', models.CharField(choices=[('10', '10º Ano'), ('11', '11º Ano'), ('12', '12º Ano'), ('todos', 'Todos os Anos')], default='todos', max_length=10)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
