# Generated by Django 5.2.8 on 2026-04-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anuncio',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='destinatario',
        ),
        migrations.DeleteModel(
            name='DefinicaoPlataforma',
        ),
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
