# Generated by Django 5.2.7 on 2026-01-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('tgpsi', 'TGPSI'), ('tag', 'TAG'), ('tmult', 'TMULT'), ('tsj', 'TSJ'), ('tcab', 'TCAB')], max_length=10),
        ),
    ]
