# Generated by Django 5.2.8 on 2026-04-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_suspended', models.BooleanField(default=False, verbose_name='Plataforma Suspensa')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='pontos_ajuste',
            field=models.IntegerField(default=0, verbose_name='Ajuste de Pontos'),
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('type', models.CharField(choices=[('geral', 'Geral'), ('particular', 'Particular')], default='geral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_enviados', to=settings.AUTH_USER_MODEL)),
                ('user_destiny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Destino (se particular)')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-created_at'],
            },
        ),
    ]
