# Generated by Django 5.2.11 on 2026-04-13 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_globalsetting_aluno_pontos_ajuste_aviso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail do Utilizador')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido de Reset de Senha',
                'verbose_name_plural': 'Pedidos de Reset de Senha',
            },
        ),
        migrations.AddField(
            model_name='aviso',
            name='target_course',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Curso Alvo'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='target_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ano Alvo'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='type',
            field=models.CharField(choices=[('geral', 'Geral (Todos)'), ('filtrado', 'Filtrado (Ano/Curso)'), ('particular', 'Particular (Individual)')], default='geral', max_length=15),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='user_destiny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Destino'),
        ),
    ]
