# Generated by Django 5.2.11 on 2026-04-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_passwordresetrequest_aviso_target_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='Ficheiro (Imagem/Vídeo)'),
        ),
    ]
