# Generated by Django 5.2.8 on 2026-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_banner_image_banner_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='Arquivo'),
        ),
    ]
