# Generated by Django 5.2.8 on 2026-04-14 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_banner_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='banners/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('geral', 'Geral'), ('filtrado', 'Filtrado'), ('particular', 'Particular')], max_length=20)),
                ('target_course', models.CharField(blank=True, max_length=50, null=True)),
                ('target_year', models.CharField(blank=True, max_length=10, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_avisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='author',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='user_destiny',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='GlobalSetting',
        ),
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='pontos_ajuste',
        ),
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
