# Generated by Django 5.2.8 on 2026-04-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homebanner_platformsettings_systemaviso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='last_notifications_run',
            field=models.DateField(blank=True, null=True),
        ),
    ]
