# Generated by Django 5.2.11 on 2026-04-17 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_platformsettings_last_notifications_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='avatar/parts/')),
                ('z_index', models.IntegerField(default=0)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1.0)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['z_index'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='patinho_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Patinho'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pontos_gastos',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos Gastos'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ano_inicio',
            field=models.CharField(choices=[('22', 'Matrícula em 2022'), ('23', 'Matrícula em 2023'), ('24', 'Matrícula em 2024'), ('25', 'Matrícula em 2025'), ('26', 'Matrícula em 2026')], max_length=2, verbose_name='Ano de Matrícula'),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='outfits/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outfits', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='outfits/parts/')),
                ('z_index', models.IntegerField(default=0)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='home.outfit')),
            ],
            options={
                'ordering': ['z_index'],
            },
        ),
        migrations.CreateModel(
            name='UserAvatarState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_emotion', models.CharField(default='normal', max_length=50)),
                ('active_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.outfit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'outfit')},
            },
        ),
    ]
