# Generated by Django 5.2.11 on 2026-04-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_avatarpart_aluno_patinho_nome_aluno_pontos_gastos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitpart',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
