# Generated by Django 5.2.11 on 2026-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_outfitpart_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitpart',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
