# Generated by Django 5.2.11 on 2026-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='allow_files',
            field=models.BooleanField(default=False, verbose_name='Permitir Envio de Arquivos'),
        ),
        migrations.AddField(
            model_name='publication',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='publication',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Realização'),
        ),
        migrations.AddField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração (Exclusão)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link (Opcional)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='needs_approval',
            field=models.BooleanField(default=False, verbose_name='Requer Aprovação de Inscrição'),
        ),
        migrations.AddField(
            model_name='publication',
            name='participant_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Participantes'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('TAREFA', 'Tarefa'), ('CONCURSO', 'Concurso'), ('PROJETO', 'Projeto'), ('EVENTO', 'Evento')], default='PROJETO', max_length=20, verbose_name='Tipo de Publicação'),
        ),
        migrations.AddField(
            model_name='publication',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
