# Generated by Django 5.2.11 on 2026-03-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_concurso_evento_projeto_tarefa_delete_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='event_date',
        ),
        migrations.AddField(
            model_name='concurso',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='publications/documents/', verbose_name='Documento/Edital'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='secondary_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary', to=settings.AUTH_USER_MODEL, verbose_name='Autor Secundário (Aluno)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AddField(
            model_name='evento',
            name='secondary_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary', to=settings.AUTH_USER_MODEL, verbose_name='Autor Secundário (Aluno)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='publications/documents/', verbose_name='Documento do Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='secondary_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary', to=settings.AUTH_USER_MODEL, verbose_name='Autor Secundário (Aluno)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='secondary_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary', to=settings.AUTH_USER_MODEL, verbose_name='Autor Secundário (Aluno)'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Início'),
        ),
    ]
