# Generated by Django 5.2.11 on 2026-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_evento_event_date_concurso_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='course',
            field=models.CharField(choices=[('gestao', 'Gestão e Programação de Sistemas Informáticos'), ('multimedia', 'Multimédia'), ('artes', 'Artes Gráficas'), ('juridicos', 'Jurídicos'), ('cabeleireiro', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='course',
            field=models.CharField(choices=[('gestao', 'Gestão e Programação de Sistemas Informáticos'), ('multimedia', 'Multimédia'), ('artes', 'Artes Gráficas'), ('juridicos', 'Jurídicos'), ('cabeleireiro', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='course',
            field=models.CharField(choices=[('gestao', 'Gestão e Programação de Sistemas Informáticos'), ('multimedia', 'Multimédia'), ('artes', 'Artes Gráficas'), ('juridicos', 'Jurídicos'), ('cabeleireiro', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
    ]
