# Generated by Django 5.2.11 on 2026-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_concurso_course_projeto_course_tarefa_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='school_year',
            field=models.CharField(choices=[('10', '10º Ano'), ('11', '11º Ano'), ('12', '12º Ano'), ('todos', 'Todos os Anos')], default='todos', max_length=10, verbose_name='Ano Escolar'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='school_year',
            field=models.CharField(choices=[('10', '10º Ano'), ('11', '11º Ano'), ('12', '12º Ano'), ('todos', 'Todos os Anos')], default='todos', max_length=10, verbose_name='Ano Escolar'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='school_year',
            field=models.CharField(choices=[('10', '10º Ano'), ('11', '11º Ano'), ('12', '12º Ano'), ('todos', 'Todos os Anos')], default='todos', max_length=10, verbose_name='Ano Escolar'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='course',
            field=models.CharField(choices=[('GPSI', 'Gestão e Programação de Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data para Exclusão do Arquivo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='course',
            field=models.CharField(choices=[('GPSI', 'Gestão e Programação de Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='course',
            field=models.CharField(choices=[('GPSI', 'Gestão e Programação de Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Serviços Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='participant_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Participantes'),
        ),
    ]
