# Generated by Django 5.2.11 on 2026-03-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_concurso_school_year_projeto_school_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('tarefa', 'Tarefa'), ('concurso', 'Concurso')], max_length=20, verbose_name='Tipo de Post')),
                ('post_id', models.PositiveIntegerField(verbose_name='ID do Post')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Inscrição')),
                ('descricao', models.TextField(verbose_name='Descrição da Inscrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='inscriptions/files/', verbose_name='Arquivo da Inscrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('user', 'post_type', 'post_id')},
            },
        ),
    ]
