# Generated by Django 5.2.11 on 2026-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='evento',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
