# Generated by Django 5.2.11 on 2026-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_concurso_views_count_evento_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='course',
            field=models.CharField(choices=[('GPSI', 'Gestão e Programação de Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Serviços Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='evento',
            name='school_year',
            field=models.CharField(choices=[('10', '10º Ano'), ('11', '11º Ano'), ('12', '12º Ano'), ('todos', 'Todos os Anos')], default='todos', max_length=10, verbose_name='Ano Escolar'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='course',
            field=models.CharField(choices=[('GPSI', 'Gestão e Programação de Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Serviços Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='course',
            field=models.CharField(choices=[('GPSI', 'Gestão e Programação de Sistemas Informáticos'), ('MULT', 'Multimédia'), ('AG', 'Artes Gráficas'), ('SJ', 'Serviços Jurídicos'), ('CAB', 'Cabeleireiro'), ('nenhum', 'Nenhum (Todos os cursos)')], default='nenhum', max_length=50, verbose_name='Curso'),
        ),
    ]
