# Generated by Django 5.2.8 on 2026-04-08 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_evento_course_evento_school_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='winner_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concurso_winner_1', to=settings.AUTH_USER_MODEL, verbose_name='1º Lugar'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='winner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concurso_winner_2', to=settings.AUTH_USER_MODEL, verbose_name='2º Lugar'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='winner_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concurso_winner_3', to=settings.AUTH_USER_MODEL, verbose_name='3º Lugar'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Estado da Inscrição'),
        ),
    ]
