# Generated by Django 5.2.11 on 2026-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_concurso_winner_1_concurso_winner_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='evento',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
