# Generated by Django 5.2.8 on 2026-04-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_concurso_archived_at_concurso_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='concurso',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='is_archived',
        ),
    ]
