# Generated by Django 5.2.8 on 2026-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_remove_concurso_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='notified_approaching_end',
            field=models.BooleanField(default=False, verbose_name='Notificado: Prazo Próximo'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='notified_finished',
            field=models.BooleanField(default=False, verbose_name='Notificado: Finalizado'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='notified_approaching_end',
            field=models.BooleanField(default=False, verbose_name='Notificado: Prazo Próximo'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='notified_finished',
            field=models.BooleanField(default=False, verbose_name='Notificado: Finalizado'),
        ),
    ]
